// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCejq5T6fTM1GtOZtHtK5jhbsrd0m2Xyb4',
    appId: '1:855259393790:web:ca4c52681389809bbf7faf',
    messagingSenderId: '855259393790',
    projectId: 'pet-information-f7bac',
    authDomain: 'pet-information-f7bac.firebaseapp.com',
    storageBucket: 'pet-information-f7bac.firebasestorage.app',
    measurementId: 'G-R0FW4BPFDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHtedwp9suTw1ZY5C6ZWeLen0DmLLUa08',
    appId: '1:855259393790:android:97298beff3b5eb28bf7faf',
    messagingSenderId: '855259393790',
    projectId: 'pet-information-f7bac',
    storageBucket: 'pet-information-f7bac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzGOGOzidYFF6W5Xtfy1N_LGs16ZweELM',
    appId: '1:855259393790:ios:d4bbbd95927f5ce5bf7faf',
    messagingSenderId: '855259393790',
    projectId: 'pet-information-f7bac',
    storageBucket: 'pet-information-f7bac.firebasestorage.app',
    iosBundleId: 'com.example.petInformation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzGOGOzidYFF6W5Xtfy1N_LGs16ZweELM',
    appId: '1:855259393790:ios:d4bbbd95927f5ce5bf7faf',
    messagingSenderId: '855259393790',
    projectId: 'pet-information-f7bac',
    storageBucket: 'pet-information-f7bac.firebasestorage.app',
    iosBundleId: 'com.example.petInformation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCejq5T6fTM1GtOZtHtK5jhbsrd0m2Xyb4',
    appId: '1:855259393790:web:e1ca5f03726640b9bf7faf',
    messagingSenderId: '855259393790',
    projectId: 'pet-information-f7bac',
    authDomain: 'pet-information-f7bac.firebaseapp.com',
    storageBucket: 'pet-information-f7bac.firebasestorage.app',
    measurementId: 'G-YFK7D3SQ0X',
  );
}
